### PR TITLE
Improve FakeClient with fake methods

### PR DESCRIPTION
**Pull request by djmitche**
Some of the methods do some debug logging in hopes of avoiding confusion
over why callbacks weren't called.

/cc @ydidwania

### CODE REVIEW

**Review by ydidwania — APPROVED** [review]
Looks good to me. These will definitely make writing tests easier

**Comment by djmitche** [comment]
v11.1.1

@ydidwania if you want to make a PR to use these new features, feel free (but don't feel obligated)

**Comment by ydidwania** [comment]
@djmitche I would probably do it when we are working on the blacklisting. Do let me know if you'd need it before you work on improving the testing

**Comment by djmitche** [comment]
No rush - it's strictly a nice-to-have refactor.

**Pull request merged**
